SUBROUTINE BET_WRITE_POLARS(SECTION_CHAR, ALPHA)

IMPLICIT NONE

CHARACTER(LEN=1), INTENT(IN) :: SECTION_CHAR

REAL*8, INTENT(IN) :: ALPHA

CHARACTER(LEN=30) :: RESULT_FILE, POLAR_FILE

CHARACTER(LEN=5), DIMENSION(1:5) :: C1

REAL*8, DIMENSION(1:4) :: COEFF

INTEGER :: I, ERROR

LOGICAL :: EXISTS



RESULT_FILE = "CL.dat"

POLAR_FILE = "polar_auto"//SECTION_CHAR//".dat"

OPEN(UNIT=1, FILE=RESULT_FILE)

DO I = 1,4
    READ(1, *, IOSTAT=ERROR)
    IF (ERROR/=0) EXIT
END DO

READ(1, *, IOSTAT=ERROR) (C1(I), C1(I+1), COEFF(I), I=1,4)

IF (ERROR==0) THEN

    INQUIRE(FILE=TRIM(ADJUSTL(POLAR_FILE)), EXIST=EXISTS)

    IF (EXISTS) THEN
        OPEN(UNIT=2, FILE=POLAR_FILE, POSITION="APPEND")
    ELSE
        OPEN(UNIT=2, FILE=POLAR_FILE, STATUS="NEW")
    END IF

    WRITE(2, '(F5.2, 2(F8.5))') ALPHA, COEFF(1), COEFF(2)

    CLOSE(2)

END IF

CLOSE(1)

END SUBROUTINE BET_WRITE_POLARS