SUBROUTINE WRITE_AOACLCD(POSITION, AOA, CL, CD)

USE MOD_BET

IMPLICIT NONE

REAL*8, INTENT(IN) :: POSITION, AOA, CL, CD

CHARACTER(LEN=255) :: PATH

LOGICAL :: EXISTS

PATH = "Clcd_section.dat"

INQUIRE(FILE=PATH, EXIST=EXISTS)

IF (EXISTS) THEN
    
     OPEN(UNIT=1,FILE=PATH,FORM="formatted",POSITION="APPEND")

ELSE
    
     OPEN(UNIT=1,FILE=PATH,FORM="formatted")

     WRITE(1,'("#", 4(A8 ,3X), "#")') "r/R", "AOA","CL", "CD"

END IF

WRITE(1, '(F9.3, 1X, F9.3, 1X, 2(F9.3,1X))') POSITION/BET_R, AOA*180.0D0/PI, CL, CD

END SUBROUTINE