MODULE MOD_BET

REAL*8, PARAMETER :: PI = 3.141593

! BET PARAMETERS FILE
CHARACTER(LEN=*), PARAMETER :: BET_PARAM_FILE="./bet_param.dat"

! FLUID DENSITY
REAL*8 :: BET_RHO

REAL*8 :: BET_RPM_START
REAL*8 :: BET_RPM_STEP
INTEGER :: BET_RPM_NUMBER

!
REAL*8 :: BET_NBLADES

!
REAL*8 :: BET_R

!
INTEGER :: BET_NSEC

!
REAL*8 :: BET_VIT

!
REAL*8 :: BET_Lref

!
REAL*8 :: BET_mu

!
REAL*8 :: BEM_COEF_MAXVAR

!
REAL*8 :: BEM_COEF_MAXIT

!
CHARACTER(LEN=60) :: BET_FBLADE

!
CHARACTER(LEN=60) :: BET_FTAB

!
CHARACTER(LEN=60) :: BET_FOUT


NAMELIST /PARAM_BET/ BET_RHO, BET_NBLADES, BET_R, BET_NSEC, BET_VIT, BET_Lref, BET_mu, BET_FBLADE, BET_FTAB, BET_FOUT, BEM_COEF_MAXVAR, BEM_COEF_MAXIT, BET_RPM_START, BET_RPM_STEP, BET_RPM_NUMBER

END MODULE MOD_BET